This notebook is inspired from:
[Jake VanderPlas - Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/index.html)

# Numpy

In [12]:
## importing numpy
import numpy as np

np.__version__

'1.16.5'

## Creating Numpy Arrays

__From lists__

In [13]:
my_array1 = np.array([4, 1, 7, 13, 2.76])
print(my_array1.shape)

my_array2 = np.array([[4, 1, 7, 13, 2.76]])
print(my_array2.shape)

(5,)
(1, 5)


In [14]:
# if we want we can also specify the data types
int_array = np.array([4, 1, 7.5, 13, 2.76], dtype = 'int32')

In [15]:
# but aware that they have certain range and limitations.


Unlike lists, arrays can be multidimensional

In [16]:
multidim = np.array([[1,2,3,12],
          [4,5,6,11], 
          [7,8,9,10]])

In [17]:
multidim.shape

(3, 4)

__From Scratch__

In [18]:
# we can create a numpy array with zeros of any shape
np.zeros((6,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
## Again we can pass the dtype

np.zeros((2,6), dtype = float)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [20]:
# we can create an array of any shape filled with any number:

np.full((3, 7), .23)

array([[0.23, 0.23, 0.23, 0.23, 0.23, 0.23, 0.23],
       [0.23, 0.23, 0.23, 0.23, 0.23, 0.23, 0.23],
       [0.23, 0.23, 0.23, 0.23, 0.23, 0.23, 0.23]])

In [21]:
## np.ones?

Other useful methods for creating arrays:

- `np.arrange`

- `np.linspace`

- `np.random.random`

## Descriptive Statistics with Numpy

In [22]:
## let's create a sample from normally distributed population of size = 10

In [23]:
## what is the mean of sample1?

In [24]:
## what is the median of sample1?

In [25]:
## sorting sample1


In [26]:
## what is the 0.1 percentile of sample1?

In [27]:
## Where is the max/min in sample1

In [28]:
## We can use different formattings as we print values
print('Maximum of sample1 is %.2f'%sample1.max())
print('The index of the max in sample1 is {}'.format(sample1.argmax()))

NameError: name 'sample1' is not defined

[Comparison between % and format](https://stackoverflow.com/questions/5082452/string-formatting-vs-format)

[Descriptive Statistics](https://www.hackerearth.com/blog/developers/descriptive-statistics-python-numpy/)